### ISSUE TITLE
2.8.2版本遇到一些bug

### ISSUE THREAD

**Issue by MachMY** [xing-yv/fanqie-novel-download#22]
问题1）
![Screenshot (13374)](https://github.com/xing-yv/fanqie-novel-download/assets/145979774/87128511-bf1d-4319-8c77-364de22f79f1)
![Screenshot (13375)](https://github.com/xing-yv/fanqie-novel-download/assets/145979774/efc7dd00-45f6-4001-86d4-317e2060269d)
用2.8.2版本更新或下载小说，会导致同一章节重复下载两次
卸载后,重启电脑,再安装无法解决问题

问题2）
移至 #23 

2.8.1版本没这两个问题

我下载的是fanqie_tool_windows_v2.8.2.exe
操作系统Windows10

**Comment by xing-yv** [comment]
第一个问题在
Windows 11 22621.2715系统
和Windows 10 x64 19045.3448
并未复现
能否提供出现问题的章节链接和您的系统版本号
（[获取系统版本号](https://support.microsoft.com/zh-cn/windows/%E6%88%91%E8%BF%90%E8%A1%8C%E7%9A%84%E6%98%AF%E5%93%AA%E4%B8%AA-windows-%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E7%89%88%E6%9C%AC-628bec99-476a-2c13-5296-9dd081cdd808#WindowsVersion=Windows_11)）
第二个问题正在尝试复现

**Comment by MachMY** [comment]
在我的电脑，所有目录链接都会遇到这两个情况

Windows10
Microsoft Windows
Version 22H2 (OS Build 19045.3693)

我下载时是输入1，然后目录链接，然后按Enter三次
我批量更新时是输入7，然后按2，然后按Enter两次


补充）
-我是马来西亚人，没用过vpn
-用2.8.1版本更新2.8.2版本下载的小说时，会重新开始下载成不重复章节的

我尝试复现问题1，结果跑出来
![image](https://github.com/xing-yv/fanqie-novel-download/assets/145979774/d0283959-e517-45f2-94c3-9763ee82ae5d)
后闪退

我尝试复现问题2，结果跑出来
![image](https://github.com/xing-yv/fanqie-novel-download/assets/145979774/86a65f21-f337-419d-91ce-80620fb03ced)
后闪退 (用OBS录的,然后截图）

**Comment by xing-yv** [comment]
在问题修复之前，请考虑使用正常的版本；
如果需要使用更新功能，请使用2.8之前的版本，
并停止对使用2.8.x版本更新过的小说进行再次更新；
这些小说后续普通用户大概率只能通过重新下载来使信息文件恢复正常内容。（如果您了解我的信息文件的存储方式，可以自行修改信息文件使其恢复正常）

**Comment by MachMY** [comment]
能找到问题就好 (๑•̀ㅂ•́)و✧
谢谢您

**Comment by xing-yv** [comment]
#23 更新的问题已经解决
但是我多次尝试，并未成功复现重复下载的问题，暂时也没有其他人向我报告此问题。
麻烦您：
1.尝试使用debug模式，查看是否会出现重复下载情况
2.请尝试使用此改版正常模式，如果问题仍能复现，请提供输出内容
[main.zip](https://github.com/xing-yv/fanqie-novel-download/files/13434159/main.zip)

**Comment by MachMY** [comment]
> #23 更新的问题已经解决 但是我多次尝试，并未成功复现重复下载的问题，暂时也没有其他人向我报告此问题。 麻烦您： 1.尝试使用debug模式，查看是否会出现重复下载情况 2.请尝试使用此改版正常模式，如果问题仍能复现，请提供输出内容 [main.zip](https://github.com/xing-yv/fanqie-novel-download/files/13434159/main.zip)

我今天复现不了重复下载的情况
2.8.3版本,2.8.2版本和main.exe都无法复现

**Comment by xing-yv** [comment]
部分复现：
批量模式稳定复现重复下载章节功能，关联 #24 
正在尝试修复
