### ISSUE TITLE
下载异常关闭 & 更新书籍功能无法执行 & 批量下载功能异常

### ISSUE THREAD

**Issue by Cyan-Li** [xing-yv/fanqie-novel-download#24]
1.单本下载时，书本章节较多时有几率中途失败，且没有看到报错信息，窗口自身关闭了。（下载《麻衣神算子》时多次出现，由于章节较多时间较长没有全程监控）；
2.下载了部分的书籍，在首页选择更新并拖入该txt文件时，提示不是用本工具下载的（同上，《麻衣神算子》出现）；
2.使用批量下载时，下载第一本书时出现每个章节下载两次的情况，例如 第一章 第一章 第二章 第二章 第三章 第三章 ；后重新选择单本下载可以正常下载（批量下载五本，第一本为《凡骨》）

公司电脑网关限制无法上传，图片无法附上，后补充或者发交流群中

第一次使用issue功能，使用方式如有不规范之处请提出，会按要求修改。

**Comment by xing-yv** [comment]
初步回复：
**问题1**：没有看到报错信息有两种情况：1.多按了几次回车 2.程序在下载过程外出错或非正常错误
请尝试：
1.按住Windows徽标键，同时按下“R”，打开运行窗口；
2.然后输入powershell，运行
3.将程序文件托入窗口，回车执行
4.正常操作，程序如果出错，在此窗口中，错误信息将被保存

**问题2**：
请排查：
1.是否修改文件名
2.是否未完成整个下载过程（下载中中断后保存）
如果不是这些情况，
请将小说txt文件和“%USERPROFILE%/fanqie_data”文件夹中
与小说同名的.upd文件一起压缩上传

**问题3**：
请参考 #22 
请尝试是否能够稳定复现

感谢您的支持与理解 :D

**Comment by Cyan-Li** [comment]
问题3:

**Comment by Cyan-Li** [comment]
问题3：可稳定复现，版本v2.8.3 电脑系统win10   urls.txt及复现截图见附件
[Uploading 批量下载章节重复.zip…]()

**Comment by xing-yv** [comment]
问题2已复现：
批量模式稳定复现重复下载章节功能，关联 #22 
正在尝试修复

**Comment by xing-yv** [comment]
问题1复现了吗？
