### ISSUE TITLE
当下载书籍为出版物时，文本中将出现xml和html标签

### ISSUE THREAD

**Issue by weiwei-cool** [xing-yv/fanqie-novel-download#5]
例如：
[中华人民共和国刑法.txt](https://github.com/xing-yv/fanqie-novel-download/files/12905793/default.txt)

**Comment by xing-yv** [comment]
由于此类书籍的p标签含有class格式，程序未能正确识别
由于影响范围不大，将于2.4版本修复
关联： #3

**Comment by xing-yv** [comment]
如有需要，请尝试使用正则表达式替换功能删除所有html标签：
表达式：_<[^>]+>_

**Comment by weiwei-cool** [comment]
对于含class的p标签，我已修复并提交了拉取请求

**Comment by xing-yv** [comment]
原来也是开发者啊doge

**Comment by weiwei-cool** [comment]
当然

**Comment by weiwei-cool** [comment]
但值得注意的是，这个bug还没有完全解决，今天有点晚了，我明天刚好有时间来捯饬捯饬
